version: '3.12'

services:
  api:
    build:
      context: .
      target: dev
      args:
        APP_ENV: development
    command: [ "bash", "-c", "uvicorn main:app --host 0.0.0.0 --port ${SERVER_PORT} --reload" ]
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ".:/app"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 3

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"

#  alembic:
#    image: python:3.12-slim
#    command: [ "alembic", "upgrade", "head" ]
#    volumes:
#      - "/app"
#    working_dir: /app
#    depends_on:
#      db:
#        condition: service_healthy
#    environment:
#      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}
#    env_file:
#      - .env

volumes:
  postgres_data:
    
