"""upd_quiz

Revision ID: 70276e66de98
Revises: bf8e1e200aa9
Create Date: 2025-02-04 18:11:28.107862

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70276e66de98"
down_revision: Union[str, None] = "bf8e1e200aa9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_quiz_question_title", "questions", ["quiz_id", "title"]
    )
    op.create_unique_constraint(
        "uq_company_quiz_title", "quizzes", ["company_id", "title"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_company_quiz_title", "quizzes", type_="unique")
    op.drop_constraint("uq_quiz_question_title", "questions", type_="unique")
    # ### end Alembic commands ###
