"""upd_ondelete

Revision ID: 00ec5a1c83df
Revises: ae767585a299
Create Date: 2025-02-01 17:16:45.731386

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00ec5a1c83df"
down_revision: Union[str, None] = "ae767585a299"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("companies_owner_id_fkey", "companies", type_="foreignkey")
    op.create_foreign_key(
        None, "companies", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "company_user_roles_company_id_fkey", "company_user_roles", type_="foreignkey"
    )
    op.drop_constraint(
        "company_user_roles_user_id_fkey", "company_user_roles", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "company_user_roles",
        "companies",
        ["company_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "company_user_roles", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("invites_company_id_fkey", "invites", type_="foreignkey")
    op.drop_constraint("invites_user_id_fkey", "invites", type_="foreignkey")
    op.create_foreign_key(
        None, "invites", "companies", ["company_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "invites", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "invites", type_="foreignkey")
    op.drop_constraint(None, "invites", type_="foreignkey")
    op.create_foreign_key(
        "invites_user_id_fkey", "invites", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "invites_company_id_fkey", "invites", "companies", ["company_id"], ["id"]
    )
    op.drop_constraint(None, "company_user_roles", type_="foreignkey")
    op.drop_constraint(None, "company_user_roles", type_="foreignkey")
    op.create_foreign_key(
        "company_user_roles_user_id_fkey",
        "company_user_roles",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        "company_user_roles_company_id_fkey",
        "company_user_roles",
        "companies",
        ["company_id"],
        ["id"],
    )
    op.drop_constraint(None, "companies", type_="foreignkey")
    op.create_foreign_key(
        "companies_owner_id_fkey", "companies", "users", ["owner_id"], ["id"]
    )
    # ### end Alembic commands ###
