"""upd_quiz

Revision ID: 87e978d4b4b9
Revises: a62cbcc244c3
Create Date: 2025-02-04 09:11:25.564695

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87e978d4b4b9"
down_revision: Union[str, None] = "a62cbcc244c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
