name: Check code quality

on:
  - pull_request

jobs:
  code-qality:
    runs-on: ubuntu-latest
    env:
      DEBUG: 1
      SERVER_PORT: 8080
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
      DB_HOST: db-test
      DB_PORT: 5432
      BROKER_URL: "redis://broker:6379/0"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install poetry
        run: pip install poetry && poetry install
      - name: Run formatters
        run: poetry run black --check . && poetry run isort --check . --profile black
      - name: Run tests
        run: docker compose -f docker-compose.test.yml up  --force-recreate --renew-anon-volumes api-test || exit 1
